on:
  push:
    branches:
      - master






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ' befor printing folder content'
        run: ls

      - uses: actions/checkout@v3
      
      - name: 'after printing folder content'
        run: ls
   